### ISSUE TITLE
Count medication status for Pharmacy First medications codelists

### ISSUE THREAD

**Issue by milanwiedemann** [opensafely/pharmacy-first-data-development#14]
We dont know whether the medication status for PF supplied medications will be different to the status of GP supplied medications. To check this, we will count the medication status for Pharmacy First medications before and after PF launch date:

1. Import all of the below codelists and merge into one large codelist
   - https://www.opencodelists.org/codelist/opensafely/pharmacy-first-acute-otitis-media-treatment-dmd/4122468e/
   - https://www.opencodelists.org/codelist/opensafely/pharmacy-first-impetigo-treatment-dmd/708e6d02/
   - https://www.opencodelists.org/codelist/opensafely/pharmacy-first-infected-insect-bites-treatment-dmd/2812d359/
   - https://www.opencodelists.org/codelist/opensafely/pharmacy-first-shingles-treatment-dmd/3bbcc6a2/
   - https://www.opencodelists.org/codelist/opensafely/pharmacy-first-sinusitis-treatment-dmd/0f036024/
   - https://www.opencodelists.org/codelist/opensafely/pharmacy-first-sore-throat-treatment-dmd/2ac5934f/
   - https://www.opencodelists.org/codelist/opensafely/pharmacy-first-urinary-tract-infection-treatment-dmd/54cc39d7/
2. Select all medications events with codes from the codelists above and add counts for each indivitual medication status

**Comment by milanwiedemann** [comment]
we need to also increase the timeframe pre and post to 6m

**Comment by chrisjwood16** [comment]
Updated for clarify/ full scope of agreed plan:
Details for `medication status` in the `medications` table has previously not been explored. We expect that as medications are issued from a community pharmacy under a PGD for the Pharmacy First service they may have a different `medication status` from standard GP acute prescriptions. We might be able to leverage this to identify medications supplied via Pharmacy First service with more specificity.

To understand this field better, we first extract the `medication status` associated with **any** entries in the `medications` table over a one year period - e.g. Aug 23 to July 24 - then we count each status across that time period.

We then extract the `medication status` associated with entries in the `medications` table that are in any of the Pharmacy First medication codelists (detailed above) - 6 months before and after PF launch to see if there is any noticeable change across these medications following launch of the Pharmacy First service.

We then extract the `medication status` associated with entries in the `medications` table that are in any of the Pharmacy First medication codelists (detailed above) for patients that ALSO have a pharmacy first clinical event code for that month - 6 months before and after PF launch to see if there is any noticeable change across these medications following launch of the Pharmacy First service.
